---
- name: "Directory Exists | {{ elasticsearch_runtime_root }}"
  file:
    state: directory
    path: "{{ elasticsearch_runtime_root }}"
    owner: "{{ elasticsearch_user }}"
    group: wcmetrics
    mode: 0775
  tags:
    - directory-structure
    - runtime-data
    - elasticsearch

- name: Upload Config | monit | elasticsearch
  template:
    src: etc/monit/conf.d/elasticsearch
    dest: /etc/monit/conf.d/elasticsearch
  notify: Reload Service | monit
  tags:
    - elasticsearch
    - using-monit

- name: Trigger All Callbacks
  meta: flush_handlers
