---
- name: Import Signing Key | Elasticsearch.org
  apt_key:
    state: present
    url: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
  tags:
    - elasticsearch

- name: Import Repository | Elasticsearch
  apt_repository:
    state: present
    repo: 'deb http://packages.elasticsearch.org/elasticsearch/1.2/debian stable main'
  notify: Update Package Cache
  tags:
    - elasticsearch

- name: Trigger All Callbacks
  meta: flush_handlers
